# OpenEdx Platform details
# mongo Details
mongo_server: ""
mongo_pwd: ""
mongo_user: ""
mongo_port: "27017"
mongo_authSource: ""

# MySQL server Details
mysql_server: ""
mysql_pwd: ""
mysql_user: ""
mysql_port: "3306"
